package generate

const (
	maxAmountOfVersions = 3
)

var externalServices = []string{
	"github.com",
	"stackoverflow.com",
	"jiathis.com",
	"amazon.co.uk",
	"eventbrite.com",
	"bbc.co.uk",
	"cnn.com",
	"usgs.gov",
	"randomlists.com",
	"yellowbook.com",
	"sogou.com",
	"cafepress.com",
	"utexas.edu",
	"etsy.com",
	"liveinternet.ru",
	"slashdot.org",
	"tamu.edu",
	"diigo.com",
	"xinhuanet.com",
	"newsvine.com",
	"yahoo.co.jp",
	"dedecms.com",
	"digg.com",
	"bravesites.com",
	"youku.com",
	"netscape.com",
	"blogger.com",
	"illinois.edu",
	"imdb.com",
	"psu.edu",
	"mozilla.com",
	"washington.edu",
	"kickstarter.com",
	"lycos.com",
	"fc2.com",
	"mit.edu",
	"quantcast.com",
	"tinyurl.com",
	"addtoany.com",
	"soundcloud.com",
	"yolasite.com",
	"trellian.com",
	"wikipedia.org",
	"biblegateway.com",
	"surveymonkey.com",
	"examiner.com",
	"tripadvisor.com",
	"123-reg.co.uk",
	"nifty.com",
	"dropbox.com",
}
